export default function stateData() {
  return [
    {
      bib: 101,
      first_name: "Dora",
      last_name: "Dewing",
      judge1: 2,
      judge2: 2,
      judge3: 1,
      judge4: 2,
      judge5: 0,
    },
    {
      bib: 102,
      first_name: "Sophie",
      last_name: "Minocchi",
      judge1: 0,
      judge2: 0,
      judge3: 1,
      judge4: 0,
      judge5: 2,
    },
    {
      bib: 103,
      first_name: "Willette",
      last_name: "Romagosa",
      judge1: 2,
      judge2: 0,
      judge3: 0,
      judge4: 2,
      judge5: 2,
    },
    {
      bib: 104,
      first_name: "Camey",
      last_name: "Darree",
      judge1: 0,
      judge2: 0,
      judge3: 1,
      judge4: 2,
      judge5: 2,
    },
    {
      bib: 105,
      first_name: "Dennet",
      last_name: "Reidshaw",
      judge1: 2,
      judge2: 2,
      judge3: 1,
      judge4: 1,
      judge5: 2,
    },
  ];
}
